from split_peel.youtube import YOUTUBE_EDIT_SCOPE, YOUTUBE_SCOPES, YOUTUBE_UPLOAD_SCOPE, build_youtube_description


def test_build_youtube_description_is_public_facing():
    description = build_youtube_description(
        {"title": "The Five-Dollar Callout Ad", "beats": ["internal planning note"]},
        show_name="Final Whistle",
        tagline="The whistle goes, the takes stay loud.",
    )

    assert description == "The Five-Dollar Callout Ad\n\nThe whistle goes, the takes stay loud."
    assert "internal planning note" not in description
    assert "Generated by" not in description


def test_youtube_oauth_scopes_cover_upload_and_metadata_edits():
    assert YOUTUBE_UPLOAD_SCOPE in YOUTUBE_SCOPES
    assert YOUTUBE_EDIT_SCOPE in YOUTUBE_SCOPES
