from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from split_peel.feed import write_json


YOUTUBE_UPLOAD_SCOPE = "https://www.googleapis.com/auth/youtube.upload"
DEFAULT_YOUTUBE_CATEGORY_ID = "17"
DEFAULT_YOUTUBE_PRIVACY_STATUS = "private"


class YouTubeUploadError(RuntimeError):
    pass


@dataclass(frozen=True)
class YouTubeUploadMetadata:
    title: str
    description: str = ""
    tags: tuple[str, ...] = ()
    category_id: str = DEFAULT_YOUTUBE_CATEGORY_ID
    privacy_status: str = DEFAULT_YOUTUBE_PRIVACY_STATUS
    notify_subscribers: bool = False
    made_for_kids: bool = False
    contains_synthetic_media: Optional[bool] = None


def upload_video(
    video_path: Path,
    metadata: YouTubeUploadMetadata,
    *,
    credentials_path: Optional[Path] = None,
    token_path: Optional[Path] = None,
    thumbnail_path: Optional[Path] = None,
    out_path: Optional[Path] = None,
    dry_run: bool = False,
    service: Any = None,
) -> dict[str, Any]:
    _validate_video_path(video_path)
    _validate_metadata(metadata)
    if thumbnail_path:
        _validate_thumbnail_path(thumbnail_path)

    body = _video_resource(metadata)
    request = {
        "video": str(video_path),
        "thumbnail": str(thumbnail_path) if thumbnail_path else None,
        "part": "snippet,status",
        "notifySubscribers": metadata.notify_subscribers,
        "body": body,
    }
    if dry_run:
        result = {
            "dry_run": True,
            "uploaded_at": None,
            "video_id": None,
            "url": None,
            "request": request,
            "response": None,
            "thumbnail_response": None,
        }
        if out_path:
            write_json(out_path, result)
        return result

    youtube = service or _build_youtube_service(credentials_path, token_path)
    response = _execute_video_insert(youtube, video_path, body, metadata.notify_subscribers)
    video_id = str(response.get("id") or "")
    if not video_id:
        raise YouTubeUploadError("YouTube upload response did not include a video id")

    thumbnail_response = None
    if thumbnail_path:
        thumbnail_response = _execute_thumbnail_set(youtube, video_id, thumbnail_path)

    result = {
        "dry_run": False,
        "uploaded_at": datetime.now(timezone.utc).isoformat(),
        "video_id": video_id,
        "url": f"https://youtu.be/{video_id}",
        "request": request,
        "response": response,
        "thumbnail_response": thumbnail_response,
    }
    if out_path:
        write_json(out_path, result)
    return result


def build_youtube_description(script: dict[str, Any], *, show_name: str, tagline: str) -> str:
    lines = [
        str(script.get("title") or show_name).strip(),
        "",
        str(tagline or "").strip(),
    ]
    beats = [str(beat).strip() for beat in script.get("beats", []) if str(beat).strip()]
    if beats:
        lines.extend(["", "Episode beats:"])
        lines.extend(f"- {beat}" for beat in beats[:5])
    lines.extend(["", "Generated by the split-peel Banny Studio pipeline."])
    return "\n".join(line for line in lines if line is not None).strip()


def _validate_video_path(path: Path) -> None:
    if not path.exists():
        raise YouTubeUploadError(f"YouTube video file does not exist: {path}")
    if not path.is_file():
        raise YouTubeUploadError(f"YouTube video path is not a file: {path}")


def _validate_thumbnail_path(path: Path) -> None:
    if not path.exists():
        raise YouTubeUploadError(f"YouTube thumbnail file does not exist: {path}")
    if not path.is_file():
        raise YouTubeUploadError(f"YouTube thumbnail path is not a file: {path}")


def _validate_metadata(metadata: YouTubeUploadMetadata) -> None:
    if not metadata.title.strip():
        raise YouTubeUploadError("YouTube title is required")
    if metadata.privacy_status not in {"private", "public", "unlisted"}:
        raise YouTubeUploadError("youtube privacy status must be one of: private, public, unlisted")


def _video_resource(metadata: YouTubeUploadMetadata) -> dict[str, Any]:
    snippet: dict[str, Any] = {
        "title": metadata.title,
        "description": metadata.description,
        "categoryId": metadata.category_id,
    }
    if metadata.tags:
        snippet["tags"] = list(metadata.tags)

    status: dict[str, Any] = {
        "privacyStatus": metadata.privacy_status,
        "selfDeclaredMadeForKids": metadata.made_for_kids,
    }
    if metadata.contains_synthetic_media is not None:
        status["containsSyntheticMedia"] = metadata.contains_synthetic_media

    return {"snippet": snippet, "status": status}


def _build_youtube_service(credentials_path: Optional[Path], token_path: Optional[Path]) -> Any:
    try:
        from google.auth.transport.requests import Request
        from google.oauth2.credentials import Credentials
        from google_auth_oauthlib.flow import InstalledAppFlow
        from googleapiclient.discovery import build
    except ImportError as error:
        raise YouTubeUploadError(
            "YouTube upload requires optional Google API libraries. "
            "Install them with `pip install 'split-peel[youtube]'` or install "
            "`google-api-python-client google-auth-oauthlib google-auth-httplib2`."
        ) from error

    token_file = token_path or Path(".secrets/youtube-token.json")
    creds = None
    if token_file.exists():
        creds = Credentials.from_authorized_user_file(str(token_file), [YOUTUBE_UPLOAD_SCOPE])
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    if not creds or not creds.valid:
        if not credentials_path:
            raise YouTubeUploadError("YouTube credentials path is required for first-time authorization")
        if not credentials_path.exists():
            raise YouTubeUploadError(f"YouTube credentials file does not exist: {credentials_path}")
        flow = InstalledAppFlow.from_client_secrets_file(str(credentials_path), [YOUTUBE_UPLOAD_SCOPE])
        creds = flow.run_local_server(port=0)
    token_file.parent.mkdir(parents=True, exist_ok=True)
    token_file.write_text(creds.to_json(), encoding="utf-8")
    return build("youtube", "v3", credentials=creds)


def _execute_video_insert(youtube: Any, video_path: Path, body: dict[str, Any], notify_subscribers: bool) -> dict[str, Any]:
    try:
        from googleapiclient.http import MediaFileUpload
    except ImportError as error:
        raise YouTubeUploadError(
            "YouTube upload requires `google-api-python-client`; install `split-peel[youtube]`."
        ) from error

    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=MediaFileUpload(str(video_path), mimetype="video/*", resumable=True),
        notifySubscribers=notify_subscribers,
    )
    return request.execute()


def _execute_thumbnail_set(youtube: Any, video_id: str, thumbnail_path: Path) -> dict[str, Any]:
    try:
        from googleapiclient.http import MediaFileUpload
    except ImportError as error:
        raise YouTubeUploadError(
            "YouTube thumbnail upload requires `google-api-python-client`; install `split-peel[youtube]`."
        ) from error

    return youtube.thumbnails().set(
        videoId=video_id,
        media_body=MediaFileUpload(str(thumbnail_path), mimetype="image/*", resumable=True),
    ).execute()
